# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: archlinux-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: update
        run: pacman -Syu --noconfirm

              # Runs a single command using the runners shell
      - name: install
        run: pacman -Syu repo git neofetch htop --noconfirm

              # Runs a single command using the runners shell
      - name: cd
        run: cd ~

              # Runs a single command using the runners shell
      - name: clone
        run: git clone https://github.com/hewol/Antodroid.git

              # Runs a single command using the runners shell
      - name: rename
        run: mv Antodroid antodroid

              # Runs a single command using the runners shell
      - name: cd2
        run: cd antodroid

                      # Runs a single command using the runners shell
      - name: chmod
        run: chmod +x build-antodroid.sh

                      # Runs a single command using the runners shell
      - name: build
        run: ./build-antodroid.sh
